# Generated by Django 5.2.8 on 2025-11-25 19:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_colaborador', models.CharField(max_length=50, unique=True, verbose_name='ID Colaborador')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cargo', models.CharField(default='Operador', max_length=100)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código da Obra')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Projeto')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Projeto/Obra',
                'verbose_name_plural': 'Projetos/Obras',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Setor')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo/Descrição')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.CreateModel(
            name='Apontamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_apontamento', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('local_execucao', models.CharField(choices=[('INT', 'Dentro da obra'), ('EXT', 'Fora da obra')], default='INT', max_length=3, verbose_name='Local de Execução')),
                ('veiculo_manual_modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo (Manual)')),
                ('veiculo_manual_placa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa (Manual)')),
                ('local_inicio_jornada', models.CharField(blank=True, choices=[('OUT', 'Outros'), ('RES', 'Residência'), ('CLI', 'Cliente'), ('SED', 'Sede ATGB')], max_length=3, null=True, verbose_name='Início Jornada')),
                ('local_inicio_jornada_outros', models.CharField(blank=True, max_length=100, null=True, verbose_name='Detalhe Outros')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Início')),
                ('hora_termino', models.TimeField(verbose_name='Hora Término')),
                ('ocorrencias', models.TextField(blank=True, null=True, verbose_name='Ocorrências / Obs.')),
                ('auxiliares_extras_ids', models.CharField(blank=True, max_length=255, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('auxiliar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apontamentos_auxiliados', to='produtividade.colaborador')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtividade.colaborador', verbose_name='Colaborador')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtividade.projeto', verbose_name='Projeto')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtividade.setor', verbose_name='Setor / Justificativa')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtividade.veiculo', verbose_name='Veículo Cadastrado')),
            ],
            options={
                'verbose_name': 'Apontamento',
                'verbose_name_plural': 'Apontamentos',
                'ordering': ['-data_apontamento', '-id'],
            },
        ),
    ]
