# Generated by Django 5.2.8 on 2025-11-27 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0002_colaborador_setor_colaborador_user_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Cód. Cliente')),
                ('nome', models.CharField(max_length=255, verbose_name='Descrição/Nome')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Código do Cliente',
                'verbose_name_plural': 'Códigos do Cliente',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='apontamento',
            name='codigo_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtividade.codigocliente', verbose_name='Código do Cliente'),
        ),
    ]
