# Generated by Django 5.2.8 on 2025-11-27 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0003_codigocliente_apontamento_codigo_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigocliente',
            options={'ordering': ['codigo'], 'verbose_name': 'Código do Cliente', 'verbose_name_plural': 'Códigos de Cliente'},
        ),
        migrations.AlterField(
            model_name='codigocliente',
            name='codigo',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='O código deve ter exatamente 4 dígitos numéricos.', regex='^\\d{4}$')], verbose_name='Cód. Cliente (4 Dígitos)'),
        ),
        migrations.AlterField(
            model_name='codigocliente',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Cliente'),
        ),
    ]
