# Generated by Django 5.2.8 on 2025-11-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0004_alter_codigocliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='setores_gerenciados',
            field=models.ManyToManyField(blank=True, related_name='gestores', to='produtividade.setor', verbose_name='Setores sob Gestão (Visão Admin/Gestor)'),
        ),
    ]
