# Generated by Django 5.2.8 on 2025-12-18 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0005_colaborador_setores_gerenciados'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Centro de Custo / Justificativa')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Centro de Custo / Justificativa',
                'verbose_name_plural': 'Centros de Custo / Justificativas',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['nome'], 'verbose_name': 'Setor (Acesso/Lotação)', 'verbose_name_plural': 'Setores (Acesso/Lotação)'},
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='setor',
        ),
        migrations.AddField(
            model_name='apontamento',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtividade.centrocusto', verbose_name='Setor / Justificativa (Custo)'),
        ),
    ]
