# Generated by Django 5.2.8 on 2025-12-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0006_centrocusto_alter_setor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrocusto',
            name='permite_alocacao',
            field=models.BooleanField(default=False, help_text='Se marcado, ao selecionar este item, será solicitado o Código da Obra ou Cliente.', verbose_name='Permite alocar em Obra/Cliente?'),
        ),
    ]
