# Generated by Django 5.2.8 on 2025-12-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0007_centrocusto_permite_alocacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='apontamento',
            name='data_dorme_fora',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Pernoite'),
        ),
        migrations.AddField(
            model_name='apontamento',
            name='dorme_fora',
            field=models.BooleanField(default=False, verbose_name='Dorme Fora Nesta Data?'),
        ),
        migrations.AddField(
            model_name='apontamento',
            name='em_plantao',
            field=models.BooleanField(default=False, verbose_name='Atividade em Plantão?'),
        ),
    ]
