# Generated by Django 5.2.8 on 2025-12-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0008_apontamento_data_dorme_fora_apontamento_dorme_fora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apontamento',
            name='auxiliares_extras_ids',
        ),
        migrations.AddField(
            model_name='apontamento',
            name='auxiliares_extras',
            field=models.ManyToManyField(blank=True, related_name='apontamentos_como_extra', to='produtividade.colaborador', verbose_name='Auxiliares Extras'),
        ),
        migrations.AddField(
            model_name='apontamento',
            name='motivo_ajuste',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Ajuste'),
        ),
        migrations.AddField(
            model_name='apontamento',
            name='tem_solicitacao_ajuste',
            field=models.BooleanField(default=False, verbose_name='Possui solicitação de ajuste?'),
        ),
    ]
