# Generated by Django 5.2.8 on 2025-12-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0009_remove_apontamento_auxiliares_extras_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apontamento',
            name='solicitacao_aceita',
            field=models.BooleanField(default=False, verbose_name='Solicitação Aceita pelo Gestor?'),
        ),
    ]
