# Generated by Django 5.2.8 on 2025-12-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0010_apontamento_solicitacao_aceita'),
    ]

    operations = [
        migrations.AddField(
            model_name='apontamento',
            name='ajuste_resolvido',
            field=models.BooleanField(default=False, verbose_name='Ajuste foi realizado/concluído?'),
        ),
    ]
