# Generated by Django 5.2.8 on 2025-12-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0011_apontamento_ajuste_resolvido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apontamento',
            name='ajuste_resolvido',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='solicitacao_aceita',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='tem_solicitacao_ajuste',
        ),
        migrations.AddField(
            model_name='apontamento',
            name='status_ajuste',
            field=models.CharField(blank=True, choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado')], max_length=20, null=True, verbose_name='Status da Solicitação'),
        ),
    ]
