# Generated by Django 5.2.8 on 2026-01-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0012_remove_apontamento_ajuste_resolvido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apontamento',
            name='data_plantao',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Plantão'),
        ),
    ]
