# Generated by Django 5.2.8 on 2026-01-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0013_apontamento_data_plantao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apontamento',
            name='local_inicio_jornada',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='local_inicio_jornada_outros',
        ),
        migrations.AlterField(
            model_name='apontamento',
            name='data_dorme_fora',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Dorme-Fora'),
        ),
    ]
