# Generated by Django 5.2.8 on 2026-01-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0014_remove_apontamento_local_inicio_jornada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apontamento',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='apontamento',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
