# Generated by Django 5.2.8 on 2026-01-27 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0015_apontamento_latitude_apontamento_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['nome'], 'verbose_name': 'Setor da Empresa', 'verbose_name_plural': 'Setores da Empresa'},
        ),
        migrations.AddField(
            model_name='apontamento',
            name='contagem_edicao',
            field=models.IntegerField(default=0, verbose_name='Qtd. Edições Realizadas'),
        ),
        migrations.AddField(
            model_name='apontamento',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição (Gerente)'),
        ),
        migrations.AddField(
            model_name='apontamento',
            name='status_aprovacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente de Aprovação'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado / Ajuste Necessário')], default='PENDENTE', max_length=20, verbose_name='Status Workflow'),
        ),
        migrations.AlterField(
            model_name='apontamento',
            name='motivo_ajuste',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Ajuste (Solicitação)'),
        ),
        migrations.AlterField(
            model_name='apontamento',
            name='status_ajuste',
            field=models.CharField(blank=True, choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado')], max_length=20, null=True, verbose_name='Status da Solicitação (Legado)'),
        ),
        migrations.CreateModel(
            name='ApontamentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_snapshot', models.JSONField(verbose_name='Cópia dos Dados (Snapshot)')),
                ('data_edicao', models.DateTimeField(auto_now_add=True)),
                ('numero_edicao', models.IntegerField(verbose_name='Versão da Edição')),
                ('apontamento_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_versoes', to='produtividade.apontamento', verbose_name='Apontamento Original')),
                ('editado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Editado Por')),
            ],
            options={
                'verbose_name': 'Histórico de Alteração',
                'verbose_name_plural': 'Históricos de Alterações',
                'ordering': ['-data_edicao'],
            },
        ),
    ]
