# Generated by Django 5.2.8 on 2026-01-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0016_alter_setor_options_apontamento_contagem_edicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apontamento',
            name='id_agrupamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Agrupamento (Rateio)'),
        ),
        migrations.AlterField(
            model_name='apontamento',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='apontamento',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='apontamento',
            name='status_aprovacao',
            field=models.CharField(choices=[('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('SOLICITACAO_AJUSTE', 'Solicitação de Ajuste')], default='EM_ANALISE', max_length=20, verbose_name='Status Workflow'),
        ),
    ]
